### ISSUE TITLE
Publish the new version of the theme in NPM

### ISSUE THREAD

**Issue by brenopolanski** [giliamverheide/ARK-Pure#3]
Hey @giliamverheide can you publish again your theme for the NPM? Then the preview of the images will appear in the wallet. **Do this for your 3 themes**.

See the steps here: https://blog.ark.io/how-to-develop-a-plugin-for-ark-desktop-wallet-1dc06cbed72d

**Comment by giliamverheide** [comment]
Sure, thanks for reminding me!
